### PR TITLE
Implements search for warden

### PR DESCRIPTION
**Pull request by sarthakag**
#153

### CODE REVIEW

**Comment by sarthakag** [comment]
@mehulmpt Can you review this?

**Comment by mehulmpt** [comment]
seems ok

**Comment by mehulmpt** [comment]
why `perm=int(0)` and not simply `0`? There are couple of more such lines

**Comment by mehulmpt** [comment]
Also jQuery is available as local asset, can you use that

**Comment by sarthakag** [comment]
#164

**Comment by sarthakag** [comment]
#159

**Pull request merged**
